### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by AkibAzmain** [swyddfa/esbonio#143]
I can't find any ``LICENSE`` or ``COPYING`` file in this repo. If your code has no license it doesn't mean it is in the public domain, instead, it means no one can even download it (let alone executing or modifying). I want to continue using this extension (I didn't know that it doesn't have any license, forgive me as I violated the copyright act) and modify it to fix issue #142 (that I submitted several minutes ago).

Please consider adding an [FSF approved](https://en.wikipedia.org/wiki/List_of_FSF_approved_software_licenses) license so I can continue using the software and modify it. If you don't add one, I will be forced to uninstall the extension as I don't have the permissions to use it legally (again, please forgive me as I used your useful software).

**Comment by alcarney** [comment]
My mistake! I've done a bad job of advertising it, but both the Language Server and VSCode extension are intended to be MIT licensed. I set the license in the in the extension's [package.json](https://github.com/swyddfa/esbonio/blob/develop/code/package.json#L9) and the server's [setup.cfg](https://github.com/swyddfa/esbonio/blob/develop/lib/esbonio/setup.cfg#L9) but completely forgot about adding dedicated `LICENSE` files - I'll try and add them in the next few days.

I'm glad you're finding this useful! :smile:
