### ISSUE TITLE
Convert cli arguments to configuration options

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#185]
Currently a number of "options" are set via cli arguments when launching the language server.
```
  --cache-dir CACHE_DIR
                        the directory where cached data should be stored, e.g. Sphinx build output
  --hide-sphinx-output  hide sphinx build output from the log
  --log-filter LOG_FILTER
                        only include log messages from loggers with the given name,can be set
                        multiple times.
  --log-level {error,info,debug}
                        set the level of log message to show from the language server
```

However with #160 and #161 we now have 2 options that are set via the LSP protocol itself. Should these options be converted to config options instead?  Currently I'm leaning towards "yes" as it feels more "portable" to lean on the protocol where possible plus it would simplify the startup logic for clients.

**Comment by alcarney** [comment]
Any thoughts @yaegassy? You're the only person I currently know of who would be affected by this

**Comment by yaegassy** [comment]
@alcarney I am in favor of changing it to a configuration option.
