### ISSUE TITLE
Incorrect syntax highlighting of multiple "aliased" roles on a single line

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#278]
![image](https://user-images.githubusercontent.com/2675694/149391799-406494d2-18e1-4a84-8f17-1157e50b977a.png)

**Comment by lextm** [comment]
I noticed that you resolved this by removing the grammar file you created and turning users to vscode-rst. That's a good move, but do you consider contributing the unit test cases and adapting them to the grammar file of vscode-rst? I think they are still valuable assets,

https://github.com/trond-snekvik/vscode-rst/issues/31
