### ISSUE TITLE
Implement Document Link Request/Resolve

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#294]
[documentLink/resolve](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentLink_resolve)

[textDocument/documentLink](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentLink)

As a document might contain links to images/documents, implementing document link is very important a feature.

For example, `.. image:: some_image.png` should show a document link, instead of relying on "Go to definition". That's a more intuitive way to associate files.

**Comment by lextm** [comment]
Tested more in this area via https://github.com/vscode-restructuredtext/esbonio/tree/document-link and https://github.com/vscode-restructuredtext/vscode-restructuredtext/tree/document-link

## Background
Snooty uses a TypeScript based `DocumentLinkProvider` class to extract document links (returned in `provideDocumentLinks` and powered by regular expressions),

https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/document-link/src/language-server/docLinkProvider.ts

The extracted links contain relative paths to the images/docs and later expand to full paths via `documentLink/resolve` calls to language server.

I used the forked esbonio language server to achieve the same.

## What Esbonio language server might do
I don't think Esbonio should follow Snooty's approach, and instead it should

* Implement `textDocument/documentLink` so that document links are provided by the language server directly.
* The returned links might contain full paths, so that no further call to `documentLink/resolve`.

I am not yet familiar with all the components of Esbonio, so I didn't work further on this.

**Comment by alcarney** [comment]
Thanks for digging into this more, I’d be happy to guide you through the internals if you’d like or take a look myself, which ever you think would be best
