### ISSUE TITLE
Minimal system requirements for Esbonio

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#295]
Snooty language server requires Python >=3.7 and pip >=20.1.2, so that the VSCode extension can verify if the target machine has such versions ready.

What are the minimal Python and pip versions for Esbonio language server?

**Comment by alcarney** [comment]
Minimum Python is currently >= 3.6.

I have no idea what the minimum version of pip would be…. as far as I know there’s nothing special going on with the packaging so I imagine any recent version of pip would do. Though it’s probably good to pick a version that supports `pyproject.toml` so maybe anything >= [v10](https://pip.pypa.io/en/stable/news/#id695)?

**Comment by lextm** [comment]
Then I will modify vscode-restructuredtext to allow esbonio to be used in Python 3.6 environments.

I don't know why snooty package requires 20.1.2 and above, but reading the major changes above 20.1.1 I can see that the dependency resolver has been significantly changed since then. Thus, I will keep that 20.1.2 check in vscode-restructuredtext for a while.
