### ISSUE TITLE
Problems activating esbonio v0.7.2

### ISSUE THREAD

**Issue by oharboe** [swyddfa/esbonio#296]
@David-Cowan Any tips in how I can debug this or provide more useful logging or detail?

We have a Python virtualenv set up with Esbonio(esbonio==0.8.0) installed and I try to configure Esbonio vscode plugin with:

```
    "esbonio.server.pythonPath": "${workspaceFolder}/../../workflow/.tox/py3/bin/python3",
    "esbonio.sphinx.buildDir": "${workspaceFolder}/_build",
    //"esbonio.sphinx.srcDir": ".",
```

I get this error, whether or not I configure srcDir above:

![image](https://user-images.githubusercontent.com/2798822/155873628-ca5075d5-4c26-4b7c-b86d-79d0db74e44c.png)

The Esbonio log is blank and the Esbonio Language Server has not yet started (it's stuck at "Startining...").

![image](https://user-images.githubusercontent.com/2798822/155873717-55426850-d902-4c6f-adf8-b0eb45ad26d5.png)

**Comment by alcarney** [comment]
You can up the logging level to debug by setting `esbonio.server.logLevel = “debug”`

The issue though will be your `esbonio.server.pythonPath` setting… as far as I know the `${workspaceFolder}` variable is not something we get for free - we have to implement it ourselves for each setting that we want to support it. Since I usually let the Esbonio extension use the same Python environment that’s configured through the VSCode Python extension it’s not something I’ve got around to implementing yet… :/ 

As a workaround for now you can either remove the `esbonio.server.pythonPath` setting entirely and Esbonio will use the same environment as the Python extension. Or you can set `esbonio.server.pythonPath` to the absolute path of your Python executable.

**Comment by oharboe** [comment]
> You can up the logging level to debug by setting `esbonio.server.logLevel = “debug”`
> 
> The issue though will be your `esbonio.server.pythonPath` setting… as far as I know the `${workspaceFolder}` variable is not something we get for free - we have to implement it ourselves for each setting that we want to support it. Since I usually let the Esbonio extension use the same Python environment that’s configured through the VSCode Python extension it’s not something I’ve got around to implementing yet… :/
> 
> As a workaround for now you can either remove the `esbonio.server.pythonPath` setting entirely and Esbonio will use the same environment as the Python extension. Or you can set `esbonio.server.pythonPath` to the absolute path of your Python executable.

Thanks! That fixed the pythonpath problems.

The next problem is now that I can't seem to activate Esbanio:

1. The language server starts without error messages, the HTML pages are built by the language server as I can see from the Esbanio Language server log.
2. The Esbanio log is empty. Even though I set esbonio.server.logLevel = “debug”
3. I had to manually uninstall lextudio.restructuredtext, since it seemed to conflict
4. When I edit an .rst file, and I type ":r", I get no suggestions. I would have expected to have ":ref:" suggested.

It seems like Esbanio has silently failed to activate, near as I can tell.

How can I debug this?

**Comment by alcarney** [comment]
To ask an obvious question.... have you tried reloading VSCode? 

Just tried it on my machine and it looks like the `Esbonio` log requires a reload to pick up changes to the `esbonio.server.logLevel` setting - not that I think it will help that much in your situation as once the server is up and running not much is shown there... 

![image](https://user-images.githubusercontent.com/2675694/155889593-97342bf7-36c0-42d6-b65f-30239ea8457a.png)

In terms of debugging this, assuming that the server has picked up the value of `esbonio.server.logLevel` I would expect to see output like the following appear in the `Esbonio Language Server` log as you are typing.

```
[esbonio.lsp] Completion context: CompletionContext<file:///var/home/alex/Projects/esbonio/docs/index.rst:11:17 (rst) -- <re.Match object; span=(15, 18), match=' :\n'>>
[esbonio.lsp.Directives] Match groups: {'indent': ' ', 'option': ':', 'name': None, 'value': ''}
[esbonio.lsp.Directives] Context line:
[esbonio.lsp.Directives] Context match: None
[esbonio.lsp] Completion context: CompletionContext<file:///var/home/alex/Projects/esbonio/docs/index.rst:11:17 (rst) -- <re.Match object; span=(15, 17), match=' :'>>
[esbonio.lsp] Completion context: CompletionContext<file:///var/home/alex/Projects/esbonio/docs/index.rst:11:19 (rst) -- <re.Match object; span=(15, 20), match=' :re\n'>>
[esbonio.lsp.Directives] Match groups: {'indent': ' ', 'option': ':re', 'name': 're', 'value': ''}
[esbonio.lsp.Directives] Context line:
[esbonio.lsp.Directives] Context match: None
[esbonio.lsp] Completion context: CompletionContext<file:///var/home/alex/Projects/esbonio/docs/index.rst:11:19 (rst) -- <re.Match object; span=(15, 19), match=' :re'>>
```

There should also be a collection of lines just before the start of all the sphinx build output showing all the Sphinx related values the language server has picked up which may be useful

```
[esbonio.lsp] Workspace root file:///var/home/alex/Projects/esbonio/docs
[esbonio.lsp] Sphinx Config {'version': None, 'conf_dir': None, 'src_dir': None, 'build_dir': '/var/home/alex/.config/Code/User/workspaceStorage/9306dca4a4f32bd584d25e6355f624d6/swyddfa.esbonio/sphinx', 'builder_name': 'html'}
[esbonio.lsp] Config dir /var/home/alex/Projects/esbonio/docs
[esbonio.lsp] Src dir /var/home/alex/Projects/esbonio/docs
[esbonio.lsp] Build dir /var/home/alex/.config/Code/User/workspaceStorage/9306dca4a4f32bd584d25e6355f624d6/swyddfa.esbonio/sphinx/html
[esbonio.lsp] Doctree dir /var/home/alex/.config/Code/User/workspaceStorage/9306dca4a4f32bd584d25e6355f624d6/swyddfa.esbonio/sphinx/doctrees
[esbonio.lsp] Building...
```

Lastly could you share some info on the file you are you are trying this in? Are you trying it on a blank line etc? There's always a chance you've found a bug 😅 

Another thing that may be worth trying is typing `..` on a new line and seeing if you get any suggestion for directives

**Comment by oharboe** [comment]
aaahhh.. esbonio.server.logLevel doesn't work if I set it in the workspace, it has to be at the user-level.

```
[esbonio.lsp] Workspace root file://[deleted]docs/workflow
[esbonio.lsp] Sphinx Config {'version': None, 'conf_dir': None, 'src_dir': None, 'build_dir': '[deleted]docs/workflow/_build', 'builder_name': 'html'}
[esbonio.lsp] Config dir [deleted]docs/workflow
[esbonio.lsp] Src dir [deleted]docs/workflow
[esbonio.lsp] Build dir [deleted]docs/workflow/_build/html
[esbonio.lsp] Doctree dir [deleted]docs/workflow/_build/doctrees
[esbonio.lsp] Building...


[DEBUG] Extension activated.
[DEBUG] Python extension is available
[DEBUG] Activating python extension
[DEBUG] Running Command: [deleted]docs/workflow/../../workflow/.tox/py3/bin/python3 -c import sys ; print("{0.major}.{0.minor}.{0.micro}".format(sys.version_info))
[INFO ] Python version '3.8.10'
[DEBUG] Running Command: [deleted]docs/workflow/../../workflow/.tox/py3/bin/python3 -m esbonio --version
[DEBUG] Server version '0.8.0'
[INFO ] Server version '0.8.0'
[DEBUG] Last update was 2022-02-27T20:46:45.083Z
[DEBUG] Server start command: [deleted]docs/workflow/../../workflow/.tox/py3/bin/python3 -m esbonio
[DEBUG] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"rst"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":null,"buildDir":"[deleted]docs/workflow/_build"},"server":{"logLevel":"debug","logFilter":null,"hideSphinxOutput":false}}}
[INFO ] Starting Language Server
[DEBUG] Build start.
[DEBUG] Build complete {"config":{"sphinx":{"version":"4.4.0","confDir":"[deleted]docs/workflow","srcDir":"[deleted]docs/workflow","buildDir":"[deleted]docs/workflow/_build/html","builderName":"html"},"server":{"log_level":"debug","log_filter":null,"hide_sphinx_output":false}},"error":false,"warnings":0}
[DEBUG] Ingoring tasks
[DEBUG] Ingoring extension-output-swyddfa.esbonio-#1
[DEBUG] Ingoring extension-output-swyddfa.esbonio-#1
[DEBUG] Ingoring extension-output-swyddfa.esbonio-#1
[DEBUG] Ingoring extension-output-swyddfa.esbonio-#1
[DEBUG] Ingoring extension-output-swyddfa.esbonio-#2
[DEBUG] Ingoring Untitled-1
```

When I type ".." on a blank line, there's no output in either Esbonio Language Server log nor Esbonio log.

**Comment by alcarney** [comment]
> esbonio.server.logLevel doesn’t work if I set it in the workspace, it has to be at the user-level.

Interesting… I didn’t realise that!

> When I type ".." on a blank line, there's no output in either Esbonio Language Server log nor Esbonio log.

Hmm… this is a wild guess based on the logs above, are you trying this in a brand new file (`Untitled-1`)? Do you see the same behaviour in an existing `*.rst` file?

If it’s broken even in existing rst files then I’m afraid I’m a bit stumped…. the final thing you could try would be setting `esbonio.trace.server = “verbose”` this will log every message sent between VSCode and the server to the `Esbonio` log window. It probably won’t tell us much more about what the server is doing but we’d at least be able to confirm that the VSCode is trying to do the right thing.

**Comment by oharboe** [comment]
> > esbonio.server.logLevel doesn’t work if I set it in the workspace, it has to be at the user-level.
> 
> Interesting… I didn’t realise that!
> 
> > When I type ".." on a blank line, there's no output in either Esbonio Language Server log nor Esbonio log.
> 
> Hmm… this is a wild guess based on the logs above, are you trying this in a brand new file (`Untitled-1`)? 

I did try that, but not really intentionally, I just had a new blank text editor called Untitled-1.

> Do you see the same behaviour in an existing `*.rst` file?

No, in that case I don't see the "Ignoring" output, I simply have no response in either of the Esbonio logs.

> If it’s broken even in existing rst files then I’m afraid I’m a bit stumped…. the final thing you could try would be setting `esbonio.trace.server = “verbose”` this will log every message sent between VSCode and the server to the `Esbonio` log window. It probably won’t tell us much more about what the server is doing but we’d at least be able to confirm that the VSCode is trying to do the right thing.

I get nothing in either of the logs when I enter ".." into a .rst file...

**Comment by alcarney** [comment]
Sorry, I'm struggling to figure out why you're not seeing any output at all.... :/ 
To ask a few more questions
- What OS are you using and which VSCode version are you running?
- Is it just completions that are broken or is it anything server related? e.g.
  Does Sphinx rebuild when you save files? Do Sphinx errors/warnings appear in the `Problems` list?
  Does the `Outline` window in VSCode work? (You should be able to see section titles)
- Has the server ever crashed? There is a bug currently where server crashes can cause multiple `Esbonio Language Server` log windows to appear, might be worth checking to see if you have more than one...
- Could you try this in a blank `sphinx-quickstart` project?

**Comment by oharboe** [comment]
> Sorry, I'm struggling to figure out why you're not seeing any output at all.... :/ To ask a few more questions
> 
> * What OS are you using and which VSCode version are you running?

Ubuntu 20 and 21.

> * Is it just completions that are broken or is it anything server related? e.g.
>   Does Sphinx rebuild when you save files? 

No.

> Do Sphinx errors/warnings appear in the `Problems` list?

No.

>   Does the `Outline` window in VSCode work? (You should be able to see section titles)

Yes.

> * Has the server ever crashed? There is a bug currently where server crashes can cause multiple `Esbonio Language Server` log windows to appear, might be worth checking to see if you have more than one...

There is only one Esbonio Language Server in the Output window.

> * Could you try this in a blank `sphinx-quickstart` project?
Same result.

**Comment by lextm** [comment]
@alcarney In worst cases, you might provide instructions for such users to debug the source code on their machines and that often reveals more on what's wrong.

**Comment by oharboe** [comment]
@lextm we rely a lot on vscode, so if it is not  a lot of work, this should be in our tool chest.

Thanks!

**Comment by alcarney** [comment]
Do you have the [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) extension installed? I think I’m now seeing the same behaviour as you after installing it. The current version of Esbonio provides a conflicting reStructurtedText language definition and depending on which is active the server either works or does nothing.

@lextm Good point. I’ll admit I probably rely on print debugging more often than not!

**Comment by oharboe** [comment]
> Do you have the [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) extension installed? I think I’m now seeing the same behaviour as you after installing it. The current version of Esbonio provides a conflicting reStructurtedText language definition and depending on which is active the server either works or does nothing.


I uninstall it before testing.


> 
> @lextm Good point. I’ll admit I probably rely on print debugging more often than not!

**Comment by alcarney** [comment]
So I don’t know about debugging a released version via VSCode’s debugger etc, but you could litter `rst.logger.debug(‘xxx’)` statements around in [this file](https://github.com/swyddfa/esbonio/blob/release/lib/esbonio/esbonio/lsp/__init__.py#L111) if you can find it in your virtualenv’s site-packages folder. Each of the `on_xxx` functions define how the server handles a given message in the LSP protocol.

Alternatively if you felt like it you could clone this repo and use the `VSCode + Language Server` launch configuration and debug both client and server side.

**Comment by oharboe** [comment]
@alcarney  I tried "VScode + Language Server" and chose "docs" and got:

![image](https://user-images.githubusercontent.com/2798822/156048069-fdfef146-d82a-4026-bc15-4960f037d1d0.png)


```
$ npx --version
6.14.4
$ nodejs --version
v10.19.0
```

![image](https://user-images.githubusercontent.com/2798822/156049813-e7b5b4b6-7412-4202-8ec5-335423c5be9c.png)

**Comment by alcarney** [comment]
That’s not something I’ve seen before you appear to be in the depths of VSCode itself… 

I’m assuming you’ve run `npm install` in the `code/` folder? 

There’s also a chance your node version is too old… I had to bump the CI to v14.x to something to work recently

**Comment by oharboe** [comment]
@alcarney No, I didn't know to run npm install. I'm not familar with nodejs... I know a thing or two about Python though. I'm not sure upgrading npm will be easy on Ubuntu...

**Comment by alcarney** [comment]
Give it a go and see if you can get any further…

> I’m not sure upgrading npm will be easy on Ubuntu

Perhaps this is a good excuse for me to look into setting up a devcontainer….

**Comment by oharboe** [comment]
@alcarney Does this mean that users of this plugin have to upgrade nodejs too?

**Comment by alcarney** [comment]
I don't think so? Looking into it more, the reason I had to bump the version of nodejs in CI was so that the tool used to package the extension (`vsce`) could work. I'm assuming that as long as the version of node is good enough for VSCode it's good enough for using the extension.

The nodejs part of this extension hardly does anything, the bulk of it is figuring out how it should run the Python server and pass it off to the LSP machinery inside VSCode.

**Comment by alcarney** [comment]
Did you say which version of VSCode you are using?

**Comment by oharboe** [comment]
> Did you say which version of VSCode you are using?

Ah.. Is there a e Node.js version that is shipped with vscode? Running "npm install" from the command line doesn't run the nodejs shipped with vscode, does it?

```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-97-generic
```

**Comment by alcarney** [comment]
> Running "npm install" from the command line doesn't run the nodejs shipped with vscode, does it?

No it doesn't

Also we're on the exact same version of VSCode so that can't be the cause of your original issue... sorry just to double check something, when you tried the server I assume the file was in the reStructuredText mode provided by the Esbonio extension (`rst` and not `restructuredtext`)?
![image](https://user-images.githubusercontent.com/2675694/156060153-093af3b5-8e32-4700-bc61-c2b2572221b7.png)

It seems silly of me to ask, but so far having a mode other than `rst` is the only way I've been able to reproduce your issue.

Another random thing you could try would be to open a Python file and try `:r` or `..` in a docstring as the server should also provide completions there.

**Comment by oharboe** [comment]
> > Running "npm install" from the command line doesn't run the nodejs shipped with vscode, does it?
> 
> No it doesn't
> 
> Also we're on the exact same version of VSCode so that can't be the cause of your original issue... sorry just to double check something, when you tried the server I assume the file was in the reStructuredText mode provided by the Esbonio extension (`rst` and not `restructuredtext`)? ![image](https://user-images.githubusercontent.com/2675694/156060153-093af3b5-8e32-4700-bc61-c2b2572221b7.png)

Yep, I'm using reStructuredText.

> It seems silly of me to ask, but so far having a mode other than `rst` is the only way I've been able to reproduce your issue.
> 
> Another random thing you could try would be to open a Python file and try `:r` or `..` in a docstring as the server should also provide completions there.

When I have a .py file open, I get Python mode with all the associated behaviors.

**Comment by alcarney** [comment]
@oharboe v0.7.3 of the VSCode extension and v0.9.0 of the language server have just been released, I don't suppose they will have fixed your issue?

The extension will require v1.65 of VSCode though....

**Comment by oharboe** [comment]
> @oharboe v0.7.3 of the VSCode extension and v0.9.0 of the language server have just been released, I don't suppose they will have fixed your issue?
> 
> The extension will require v1.65 of VSCode though....

What is the difference between this plugin and https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext ?

**Comment by alcarney** [comment]
The reStructuredText plugin has been around much longer than this project and is more established. 
It integrates a number of reStructuredText tools like `rstcheck` and `doc8`

The main focus of this project is the language server which aims to provide features such as autocomplete, goto definition etc. The VSCode extension in this project initially was the only way to use the language server from VSCode.

But you've found this at an interesting time, as of just a few days ago the language server has been integrated into the reStructuredText plugin. [This table](https://github.com/swyddfa/esbonio/issues/279#issuecomment-1060018657) is a good summary of the features available in the two extensions.

Where that leaves the VSCode extension in this project, I'm not entirely sure yet.... but I'm thinking it might be useful to keep around in some capacity, even if it winds up being just a reference implementation that projects like [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) and [coc-esbonio](https://github.com/yaegassy/coc-esbonio) can refer to.

@lextm, anything you'd like to add? I admit I'm not that familiar with the capabilities of the reStructuredText extension

**Comment by lextm** [comment]
@alcarney Keeping both extensions alive is more meaningful,

* Like you said, esbonio-vscode is an extension more focusing on the language server itself and you already have unit testing around it. We can use it as the playground for new things (like the new status bar menu).
* vscode-restructuredtext, however, is more customer facing (as it does serve a much larger active user base and many of them are also enterprises). So it might cherry pick things from esbonio-vscode step by step, so as to minimize the impact on existing user experience (bumping everyone to VSCode 1.65.0 at this moment is not realistic in the real world).

I shared my thoughts in #279 and also sent you both new issues (#294 #295 #304 #305 #307) and pull requests (#293 #306). And that's just the beginning.

Currently my goal is to make sure the language server can be fully tested under vscode-restructuredtext to reveal more gaps (as previously snooty language server was used). All possible improvements will be sent here for your review and consideration.

**Comment by alcarney** [comment]
> bumping everyone to VSCode 1.65.0 at this moment is not realistic in the real world

I've been thinking about this for a while... i.e. what is a realistic range of versions to maintain compatibility with? 5 most recent?, 10 most recent?, etc. I've not been able to find any numbers/guides showing how quickly new versions of VSCode are adopted.

(Note, I'm not necessarily expecting an answer, just thinking aloud at this point :smile:)

**Comment by lextm** [comment]
@alcarney big enterprise might take months to update to a newer version of VSCode, and you won't easily imagine that, right? So to be safe, I rather delay certain features for 6-12 months if they require the latest VSCode build.

**Comment by oharboe** [comment]
A problem that I've run into is that vscode is now suggesting *both* for .rst files. This is confusing for the user: there's now a choice, but no guidance...

For my part, it seems like sticking with  https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext  makes the most sense.

**Comment by alcarney** [comment]
> This is confusing for the user: there's now a choice, but no guidance...

I agree, as this is all quite recent I haven't had chance to update READMEs etc.

> For my part, it seems like sticking with https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext makes the most sense.

I take it then we don't need this issue anymore? Feel free to re-open this if that's not the case

**Comment by oharboe** [comment]
👍
