### ISSUE TITLE
getLinkInfo might fetch the HTML page and propose the link text

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#307]
Currently when the input box for "Link Text" is displayed, its default value is not very helpful.

Ideally after learning the URL to link to, the extension can send an HTTP request to query the title of the page and then present it in the input box. It might not help all the times as many real-world pages might not set a good title, but at least better than just "Link Text".

**Comment by lextm** [comment]
Implemented in vscode-restructuredtext.

**Comment by alcarney** [comment]
Just as well I think... I've been considering stripping out the editor commands from the Esbonio extension so that it's just focused on integrating what the server provides.
