### ISSUE TITLE
Esbonio cannot be found as VS Extension

### ISSUE THREAD

**Issue by danieltuzes** [swyddfa/esbonio#314]
I have Esbonio installed, but after reloading VS Code, it says Esbonio cannot be found:
![image](https://user-images.githubusercontent.com/6088393/157253445-590d917b-8e51-407b-96f6-af00859f4d40.png)

"The Esbonio Language Server is not installed in your current environment. Would you like to install it?"

**Comment by alcarney** [comment]
I can see why this might cause confusion…

Esbonio comes in 2 separate parts, there is the VSCode extension “Esbonio” which is producing this notification, but there is also the `esbonio` python package which provides the language server that powers all the features such as completions.

This notification is being shown as you have the VSCode component installed but not the Python one (which is to be expected as they are published separately), clicking ‘Yes’ here will run the `python -m pip install esbonio` command that is required to install the Python component.

Hope that helps! 😄

**Comment by danieltuzes** [comment]
Thanks @alcarney I don't really understand the point of the Esbonio VS Code extension then. I have https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext
and the esbonio pip package installed, and I can do everything that is attributed to esbonio here:
https://github.com/swyddfa/esbonio

Can I gain anything by installing the VS Code extension Esbonio?

**Comment by alcarney** [comment]
In a word no.

Esbonio's inclusion into https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext is quite a [recent development](https://github.com/vscode-restructuredtext/vscode-restructuredtext/commit/a8d317ad3f45155a7c26c2c31f1bb4709210d24a), up until then the only way to use the pip package was the Esbonio VSCode extension.

Going forward the Esbonio VSCode extension will continue more as a playground for new ideas and a reference implementation for other projects like the reStructuredText extension and [coc-esbonio](https://github.com/yaegassy/coc-esbonio)

It's just going to take a little time to update the messaging around this
