### ISSUE TITLE
Esbonio collects diagnostics for files under `venv`

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#321]
I am not sure if it is common that a sphinx project is configured with venv following the steps in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/333#issue-1046601666

Since all packages in the virtual environment are installed under `./venv` folder, any `.rst` files in those packages (such as `/venv/lib/python3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/class.rst`) are scanned by esbonio and diagnostics are added to `PROBLEMS` panel.

This is very annoying, so hope such files can be skipped.

**Comment by lextm** [comment]
It seems that the folder name can vary (not only `venv`), so the actual rule to skip can be more complex.

**Comment by alcarney** [comment]
Esbonio only converts warnings/errors raised by Sphinx into diagnostics, indeed you can see this behaviour in any default Sphinx project that has a `venv` in the same folder as its `srcDir`. 

The way to resolve it is to update the project's `conf.py` to exclude the `venv` folder
```
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "venv"]
```

**Comment by lextm** [comment]
Ah, that makes sense. Then it should be the responsibility of the VSCode extension (vscode-restructuredtext) for example, to warn users that they should exclude venv folders in `conf.py` (and maybe automate the changes).

No need to change the language server in this case.
