### ISSUE TITLE
The `esbonio.sphinx.confDir` kept being changed with absolute path.

### ISSUE THREAD

**Issue by huxuan** [swyddfa/esbonio#322]
I want to share the workspace settings with team members by add `.vscode/settings.json` in the git repo. But the `esbonio.sphinx.confDir` kept being changed by the language server. Even when I set the settings to `${workspaceRoot}/docs`, it will still be changed with the absolute path.

**Comment by lextm** [comment]
Which VSCode extension are you using?

If you are using lextudio.vscode-restructuredtext, this behavior is by design and will be resolved once #304 is closed here.

**Comment by huxuan** [comment]
@lextm Thanks for the quick reply. I noticed that issue but the problem is that the settings will be changed even after I set the `esbonio.sphinx.confDir` to `${workspaceRoot}/docs`. The overwrite behavior is not expected.

**Comment by lextm** [comment]
You might find more information around that from https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/351#issuecomment-1059908631

For vscode-restructuredtext extension users, they should keep using `restructuredtext.xxxx` settings instead of `esbonio.xxxx`, till the migration phase ends some time in the coming months.

**Comment by huxuan** [comment]
OK, that makes sense to me. Thanks for your patience and wish for the migration.

**Comment by beutlich** [comment]
Thanks for the fix. When will the new version be available at PyPi?

**Comment by lextm** [comment]
Today esbonio 0.10.0 is shipped so please upgrade vscode-restructuredtext to 179.0.0. The configuration migration logic has been revised significantly,

1. Copy raw values from `restructuredtext.xxx` to `esbonio.sphinx.xxx`.
2. Warn users to delete `restructuredtext.xxx` from config file.

This one-way migration resolves this issue.
