### ISSUE TITLE
Can Pydantic be made to warn instead of error on unexpected input?

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#333]
More details can be found in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/360

**Comment by alcarney** [comment]
I wonder if there is a way to make pydantic less strict in some scenarios...

**Comment by alcarney** [comment]
It would appear that this is [not possible](https://github.com/samuelcolvin/pydantic/issues/939)
