### ISSUE TITLE
Maybe more frequent releases of esbonio language server

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#334]
You might check how often MongoDB team ship new releases of snooty, https://github.com/mongodb/snooty-parser/releases

What I suggest is to ship new released of esbonio in a similar manner, as soon as an important PR is merged. For example, #304 #323 #320 added significant amount of features/bug fixes, so a 0.10.0 release is desired in the coming days.

**Comment by alcarney** [comment]
Makes sense, there's a few more things I'd like to get in this release but I'll definitely have something out by the weekend at the latest.

**Comment by lextm** [comment]
Look forward to the new release.

BTW, if frequent releases are a burden to you, I don't mind releasing from a fork repo under a different PyPI package name (I used to use `snooty-lextudio` instead of `snooty`).

**Comment by alcarney** [comment]
Technically, they're not a burden at all I can just open a PR against the `release` branch and let CI take it from there.
I think I just need get in the habit of releasing more often, especially now that it's more than just me interested in this! :smile:

**Comment by lextm** [comment]
Aha, just get used to this, because now you own a key piece of software in the whole ecosystem and serve hundreds of thousands of people suddenly 😆 It takes a while to adapt and keep up the good work.
