### ISSUE TITLE
Preview server fails to start on MacOS

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#341]
Unable to start the `multiprocessing.Process` for the server as it fails with an error along the lines of `Unable to pickle object _thread.lock`

**Comment by skycaptain** [comment]
The same or similar issue happens still on MacOS:

```
[esbonio.lsp] Starting preview server.
Failed to handle request 4 workspace/executeCommand work_done_token=None command='esbonio.server.preview' arguments=[CommandParams(show=False)]
Traceback (most recent call last):
 ...
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by alcarney** [comment]
That's annoying! Hopefully the same fix for Windows will work on MacOS...

**Comment by lextm** [comment]
Strange that I didn't experience any macOS issue (old 2014 MacBook Pro as well as latest MacBook Pro M1 Max). Again, bug reports lacking of details can prevent further troubleshooting.
