### ISSUE TITLE
No definition found for 'label-name'

### ISSUE THREAD

**Issue by davbeek** [swyddfa/esbonio#357]
For some references of the form:
```
:ref:`label-name`
:ref:`Description <label-name>`
```
F12 indeed opens the document where the label is defined, but in most cases, I get the pop-up: No definition found for 'label-name'.

The preview window works brilliantly, and all ref links in the preview window also work. What is wrong, or can the definition of labels be found only in specific cases?

[Link to the website](http://4tc00.wtb.tue.nl), where the label definitions can often not be found by esbonio.

Esbonio 0.10.3
VSCode 1.66.2
Esbonio VSCode extension v0.8.1
macOS Monterey 12.3

**Comment by alcarney** [comment]
Do the labels that work for you not have any `-` characters in them?

Trying this out on my machine, the server handles labels of the form `example` and `example_label` but fails on labels like `example-label`

**Comment by davbeek** [comment]
Actually, about a week ago, I changed all underscores in labels to hyphens, so most of my labels have hyphens in them. I will test later if these labels actually fail.

**Comment by davbeek** [comment]
I have checked several labels, and indeed, the only labels for which the definition lookup works, are the labels without hyphens. All labels with hyphens give the error.
