### ISSUE TITLE
Enable parallel builds

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#359]
- Make sure nothing breaks by enabling parallel builds
- Add init option to disable parallel builds

See vscode-restructuredtext/vscode-restructuredtext#380

**Comment by twodrops** [comment]
I guess sphinx parallel build is not supported under Windows and "[macOS + Py3.8](https://github.com/sphinx-doc/sphinx/pull/6879)" which could make this tricky. For us, it works fine with Docker (VsCode Devcontainer) under Windows, Linux and macOS.

**Comment by alcarney** [comment]
I think [this PR](https://github.com/sphinx-doc/sphinx/pull/9793) re-enables parallel builds for macOS at least.
