### ISSUE TITLE
Distribute as conda package

### ISSUE THREAD

**Issue by tobiasdiez** [swyddfa/esbonio#371]
It would be nice if esbonio were available on conda-forge so that one can install it via conda.

**Comment by alcarney** [comment]
I'm all for making it easier for people to get up and running :smile: 

However, I know nothing about conda packaging, do you know what it would take to make that happen?

**Comment by tobiasdiez** [comment]
I've newer contributed a package to conda-forge myself, but the process seems to be reasonably straightforward: https://conda-forge.org/docs/maintainer/adding_pkgs.html
(essentially, fork the example repo, automatically create the recipe using grayskull and then open a PR to the conda-forge repo)

**Comment by alcarney** [comment]
Looks straightforward enough.

My only concern is keeping it up to date, do you know of any projects that have automated the process of keeping a feedstock repo up to date with an upstream? If it's not automated then I'm likely to forget to keep it in sync - especially with it being off in a separate repo

**Comment by tobiasdiez** [comment]
Conda-forge is listing to updates on pypi and automatically creates a PR if a new version is published there. So the maintenance overhead should be small. See https://github.com/conda-forge/scipy-feedstock/pull/182 for an example.

**Comment by alcarney** [comment]
Oh, awesome! :D 

The docs gave me the impression it was a manual thing... anyway I'll definitely be taking a look at setting this up.

**Comment by alcarney** [comment]
I've made an initial attempt at writing a recipe in conda-forge/staged-recipes#18886

**Comment by alcarney** [comment]
Esbonio is now available on [conda-forge](https://anaconda.org/conda-forge/esbonio)! :tada: 
Thanks for requesting this, feel free to reopen this if there are any issues with the package

**Comment by davbeek** [comment]
Nice!

**Comment by tobiasdiez** [comment]
Awesome, thanks!
