### ISSUE TITLE
Output not generated directly under the build folder and pickles uses wrong default name

### ISSUE THREAD

**Issue by twodrops** [swyddfa/esbonio#373]
When a build folder is specified as follows
`esbonio.sphinx.buildDir": "${workspaceFolder}/build/`

esbonio creates the output not under this folder but under
`esbonio.sphinx.buildDir": "${workspaceFolder}/build/html`

This is different from the previous behavior in [vscode-restructuredtext](https://github.com/vscode-restructuredtext/vscode-restructuredtext) extension.

This causes incompatibility with command line sphinx-build which generates output directly under the build folder. We want to resuse the HTMLs between sphinx-cli-build and esbonio-build.

Not sure if the fix for this should be in the [vscode-restructuredtext](https://github.com/vscode-restructuredtext/vscode-restructuredtext) extension.
https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/9dfc94ec6ffab391e7c69d46a0c1101b3495a117/src/extension.ts#L124

Secondly, the pickles folder is called `doctrees` and not `.doctrees`, `.doctrees` is the default when using sphinx commandline `sphinx\cmd\build.py`.

The difference in pickles folder name breaks the incremental build between sphinx-cli-build and esbonio-build.

How about

```python
       doctreedir = os.path.join(outputdir, ".doctrees")  # use same default as in sphinx\cmd\build.py
        self.sphinx = sphinx.application.Sphinx(
            ...
            doctreedir=doctreedir,
            buildername="html",
             ...
        )
```
Similar problem is discussed [here](https://github.com/open-needs/open-needs-ide/issues/21).

**Comment by alcarney** [comment]
I'm a little confused as the described behavior seems consistent with a default `sphinx-quickstart` project

```
$ sphinx-quickstart test
Welcome to the Sphinx 4.4.0 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

...

Finished: An initial directory structure has been created

You should now populate your master file /var/home/alex/Projects/test/index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.

$ cd test
$ make html

Running Sphinx v4.4.0
...
The HTML pages are in _build/html.

$ ls _build/
doctrees/  html/
```

I'm happy to make this all configurable (by implementing something like #360), but I would assume it would make sense to be consistent with how `sphinx-quickstart` structures things?

**Comment by twodrops** [comment]
That's a good point to align with the behavior of `sphinx-quickstart` and I like it :)

`sphinx-quickstart` is creating the Makefile with `-M html`, which makes it consistent with the current esbonio behavior (`/html` folder and `doctrees` folder).

I looked it up. We changed from `-M html` to `-b html` for all our tools including [sphinx-needs](https://github.com/useblocks/sphinxcontrib-needs`), to be consistent with rST Extension (before the esbonio integration). I am pretty sure it was `-b html` before for rST Extension. This creates no `/html` folder but a `.doctrees` folder.  Perhaps  @lextm could confirm this. 

Based on the point you mentioned above (alignment to `sphinx-quickstart`), I guess we will rollback to `-M html`.

**Comment by twodrops** [comment]
I checked up the sphinx documentation again and get the feeling that `-b` is the preferred way.

For example, in the sphinx-documentation `-b` is documented first.
https://www.sphinx-doc.org/en/master/man/sphinx-build.html

`-M` documentations says:
>-M buildername
Alternative to [-b](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-b). Uses the Sphinx make_mode module, which provides the same build functionality as a default [Makefile or Make.bat](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#makefile-options).

Also see the documentation of `-d`
>-d [path](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-d)
Since Sphinx has to read and parse all source files before it can write an output file, the parsed source files are cached as “doctree pickles”. Normally, these files are put in a directory called .doctrees under the build directory.

The `.doctrees` folder is created only when `-b` is used. With `-M` the folder created is `doctrees` (without the dot)

So I am confused again :) What do you guys say @alcarney  @lextm @danwos

**Comment by alcarney** [comment]
Ultimately `esbonio` should be able to support either approach, along with any other cli options the user wishes to use.

In terms of what the default should be… I leaning towards the `sphinx-quickstart` approach simply because (I assume) it would align best with how someone new to Sphinx would use it. 

However, i’m open to being convinced otherwise 😄

**Comment by twodrops** [comment]
I asked the question in sphinx-users group.
https://groups.google.com/g/sphinx-users/c/TDVyQNP_DPs

Let's wait for some explanation 😄

**Comment by twodrops** [comment]
And the winner is `-M` 😄 
https://github.com/sphinx-doc/sphinx/issues/10422#issuecomment-1118899443

So this issue can be closed. It would be nice to have https://github.com/swyddfa/esbonio/issues/360 starting with a setting to switch between `-M` and `-b`.

Thanks for the disussion, openness and the suggestion to create a sphinx bug.

**Comment by alcarney** [comment]
Thanks for persevering!
