### ISSUE TITLE
Set default for esbonio.sphinx.numJobs as off

### ISSUE THREAD

**Issue by twodrops** [swyddfa/esbonio#374]
Proposing to leave the default value of `esbonio.sphinx.numJobs` as `off` as a lot of sphinx extensions does not support parallel build and leaves warnings in the console. Anyone wanting to use the parallel build behavior should turn it on manually. 

Also, parallel build could add unnecessary overhead to smaller projects and make is run slower.

**Comment by alcarney** [comment]
Happy to change it if it's going to cause problems, perhaps it's not the quick win I thought it would be.
Note it will also have to be changed in the vscode-restructuredtext extension, as it overrides any defaults set by the language server anyway.

cc @lextm

**Comment by lextm** [comment]
Delivered in vscode-restructuredtext 187.0.0 release.
