### ISSUE TITLE
Registering unsupported Features

### ISSUE THREAD

**Issue by danwos** [swyddfa/esbonio#384]
I'm currently trying to use the [LanguageFeatures API of esbonio](https://swyddfa.github.io/esbonio/docs/latest/en/lsp/api-reference.html#language-features) to register some features.
And I noticed that not all kinds of LSP Features are supported yet (#210, #311).
So I asked myself if there may be a generic way of registering pygls supported features, without the need for a feature-specific API in esbonio itself. 

So this issue is more about figuring out, if a generic approach is possible and if it is helpful :)

An example implementation could be: (dangerous pseudo-code, as I haven't taken a look into all sources yet):

```python
from pygls.features import HOVER

from esbonio.lsp.rst import LanguageFeature

class MyFeature(LanguageFeature):
    def __init__(self, rst, *args, **kwargs):
        super().__init__(rst, *args, **kwargs)
        self.rst = rst
        self pygls_register(HOVER, self.my_hover_function)
        
    def my_hover_function(self, *args, **kwargs):
        # do crazy stuff

```
 
Maybe also the decorator way can be used, if the pygls-server instance is somehow available.
So no pygls_register would be needed.

```python
from pygls.features import HOVER

from esbonio.lsp.rst import LanguageFeature

class MyFeature(LanguageFeature):
        
    def __init__(self, rst, *args, **kwargs):
        super().__init__(rst, *args, **kwargs)
        self.rst = rst

       @rst.pygls_instane.feature(HOVER) 
       def my_hover_function(self, *args, **kwargs):
           # do crazy stuff
```

If the above is somehow possible, I think a lot of esbonio-specific implementation time can be saved.
But I'm not sure if this fits the project goals or is technically not possible.

**Comment by danwos** [comment]
Ok, after some tests with the pygls instance inside esbonio, I think my idea is not really possible, as a LSP-Feature can be registered only once. And there may be multiple sphinx-extensions, which want to register something for the same pygls feature.

So in the end there must be at least an esbonio function, which deals with all the different feature requests by registering some kind of a manager for the specific pygls feature.

Not sure if there can be a generic manager class, which can be reused for all features.
But by looking into https://github.com/swyddfa/esbonio/blob/develop/lib/esbonio/esbonio/lsp/__init__.py it looks like the different feature-handlers are mostly specific.

I may try to implement #311 (Hover support), to know more about it :)

**Comment by alcarney** [comment]
This is certainly an interesting idea, the `rst` object passed to `esbonio_setup` is just an instance of the pygls language server object with a few extras. So, if you wanted to do a quick prototype you should be able to do something like 
```python
from pygls.features import HOVER

from esbonio.lsp.rst import LanguageFeature

class MyFeature(LanguageFeature):
    def hover(self, ...):
        ...

def esbonio_setup(rst):

    my_feature = MyFeature(rst)

    @rst.feature(HOVER)
    def on_hover(...):
        ...
        return my_feature.hover(...)
```

Granted, that doesn't help the issue of only being able to register one implementation per LSP method... perhaps it would be worth exploring overriding the default `@server.feature()` method from pygls with one that can handle multiple implementations?

> I may try to implement https://github.com/swyddfa/esbonio/issues/311 (Hover support), to know more about it :)

Go for it! You'll be able to tell me about all the terrible decisions I've made putting this together :smile: 
Feel free to ask if you have any questions
