### ISSUE TITLE
Document installing the develop version of esbonio

### ISSUE THREAD

**Issue by laundmo** [swyddfa/esbonio#396]
I just ran into #393 and wanted to still work on my project without waiting for a update. Took me a while to figure out the correct pip package path so i could install the newest version with the fix:

```
pip uninstall esbonio
pip install "git+https://github.com/swyddfa/esbonio#egg=esbonio&subdirectory=lib/esbonio"
```

Would be nice if that could be mentioned somewhere in the docs.

**Comment by alcarney** [comment]
Thanks for the suggestion - I didn't realise you could do this!
