### ISSUE TITLE
Supported Sphinx Versions?

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#401]
Currently `esbonio` is informally supporting Sphinx `2.x`, `3.x` and `4.x`, but with `5.x` now out it's probably worth thinking about what a sensible range of versions to support is.

My default stance currently is to support versions `N`, `N - 1` and `N - 2`, with `N` being the latest major version.

However, I have no idea how often people upgrade their Sphinx version so have no idea what people are actually using so would be interested to hear what people have to say

**Comment by davbeek** [comment]
I use Sphinx 4.5, since version 5 leads to dependency problems for me. I upgrade regularly.
