### ISSUE TITLE
VSCode esbonio extension uses deprecated variable ${workspaceRoot} instead of ${workspaceFolder}

### ISSUE THREAD

**Issue by davbeek** [swyddfa/esbonio#404]
VSCode has deprecated the variable `${workspaceRoot}` in favour of `${workspaceFolder}` to better align with Multi-root Workspace support, see: 

https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

The VSCode esbonio extension still uses `${workspaceRoot}`, see:

https://swyddfa.github.io/esbonio/docs/latest/en/lsp/getting-started.html?editor=vscode-esbonio#confval-esbonio.server.pythonPath-string

This is confusing, since all VSCode documentation uses `${workspaceFolder}` now.

For example, the setting `"esbonio.server.pythonPath": "${workspaceFolder}/.venv/bin/python` gives an error starting up the esbonio language server. Replacing `${workspaceFolder}` by `${workspaceRoot}` works. Removing the setting also works.

**Comment by alcarney** [comment]
Ah yes... that's not ideal. 

The simplest 'fix' would be to add `${workspaceFolder}` as an alias for the existing `${workspaceRoot}` logic in the VSCode extension - would that be sufficient for your needs?

I still haven't quite got my head around how `${workspaceFolder}` is supposed to work in a multi-root context but hopefully that can wait until #326 is tackled.

**Comment by lextm** [comment]
${workspaceRoot} is still widely used so it would be too rushed to stop supporting it. Ideally the language server should support both as valid variables in the foreseeable future.

**Comment by davbeek** [comment]
> The simplest 'fix' would be to add `${workspaceFolder}` as an alias for the existing `${workspaceRoot}` logic in the VSCode extension - would that be sufficient for your needs?

Yes, sufficient indeed, although I wonder if and when VSCode could drop support for `$(workspaceRoot}`. No idea how long they keep supporting deprecated features. Replacing `${workspaceRoot}` by `${workspaceFolder}` in the extension and adding `${workspaceRoot}` as an alias for `${workspaceFolder}` would be more work, but would perhaps be a more robust fix.

**Comment by alcarney** [comment]
As far as I know there's no API extensions can rely on for the implementation of variables like `${workspaceRoot}` which means we have to implement support for these ourselves.

On the flip side, this means we can support `${workspaceRoot}` for as long as it makes sense and there's not much difference between what is an alias for what at the moment :smile:

**Comment by davbeek** [comment]
Indeed, I was rather surprised to read that API support for variable resolving is still missing, see: 
https://github.com/microsoft/vscode/issues/140056
https://github.com/microsoft/vscode/pull/148514

Then indeed, your straightforward solution would be perfect.
