### ISSUE TITLE
Include prefix part in primary domain

### ISSUE THREAD

**Issue by stsewd** [swyddfa/esbonio#416]
Currently, esbonio will list/return only the domain part when listing domains from the primary domain

https://github.com/swyddfa/esbonio/blob/23f6032ce30ed1eaef08ee101387e99cee1531a0/lib/esbonio/esbonio/lsp/sphinx/__init__.py#L447-L449

But using the prefixed form is still valid and authors may use that form outside python docstrings to disambiguate from other domains.

This also makes the hover feature not work when used in a `:py:fun:` role, but it only works when used in `:fun:`.

I was about to make a PR making this an option, but I think maybe this should be the default behavior?

The same could be said about the `std` prefix, but I haven't that form being used in the wild.

**Comment by alcarney** [comment]
I think you're right from an API perspective, that method should definitely be returning the prefix regardless. 

Making that change however, will require refactoring the consumers of that method, otherwise completion suggestions for `:fun:` won't be generated anymore.

**Comment by stsewd** [comment]
> Making that change however, will require refactoring the consumers of that method, otherwise completion suggestions for :fun: won't be generated anymore.

Sorry I wasn't clear, I think esbonio should return both forms with and without prefix, that way hover and completion will keep working with both formats, as both are valid.

**Comment by alcarney** [comment]
Sorry, I don't think I was clear either :) 

I've just been thinking a lot about the internal API recently and it probably makes sense to adjust `get_domains` to return the prefix for all domains regardless of whether they're the primary one or not. Then generating completions for both `:py:fun:` and `:fun:` should be handled by the code that actually produces completion suggestions as directives like `.. default-domain::` can change this on a per file basis anyway.
