### ISSUE TITLE
Write a guide on setting up the language server with nvim/vim

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#45]
- [ ] [ale?](https://github.com/dense-analysis/ale), perhaps [this](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/pyls.vim) could be used as a starting point?
- [x] [coc.nvim](https://github.com/neoclide/coc.nvim) See [this](https://github.com/swyddfa/esbonio/issues/166#issuecomment-835560681) comment
- [ ] neovim's [built-in](https://neovim.io/doc/user/lsp.html) LSP client
- [ ] [vim-lsp](https://github.com/prabirshrestha/vim-lsp) See [this](https://github.com/swyddfa/esbonio/issues/166#issuecomment-835560681) comment

**Comment by cathaysia** [comment]
Today, I' trying configurate it by nvim-lspconfig. I created some files in nvim-lspconfig: https://github.com/neovim/nvim-lspconfig/pull/1395

And add some configurations for this:

```lua
return function (nvim_lsp, on_attach, capabilities)
    local servers = require("nvim-lsp-installer.servers")
    nvim_lsp.esbonio.setup{
        cmd = 'esbonio',
        on_attach = on_attach,
        capabilities = capabilities,
    }
end
```
But when I open file for this, I encounter a error:

![图片](https://user-images.githubusercontent.com/42114817/141075006-e62c491c-054d-4c83-ad1b-cee9fe2e1b7e.png)

But I can't find any log for it, how do I debugging it? Or where I wrote wrong?

**Comment by yaegassy** [comment]
@cathaysia Hi, You can look at the documentation or refer to esbonio's extension code for VSCode.

- <https://swyddfa.github.io/esbonio/docs/lsp/editors/index.html#common-configuration>
- <https://github.com/swyddfa/esbonio/blob/develop/code/src/lsp/client.ts#L15-L83>

**Comment by cathaysia** [comment]
I had read these, but I want know where I find logs?

**Comment by cathaysia** [comment]
Emm, sorry, there are some configurations I'm not list: 

```lua
local configs = require 'lspconfig/configs'
local util = require 'lspconfig/util'

configs.esbonio = {
  default_config = {
    cmd = { 'esbonio' },
    filetypes = { 'rst' },
    root_dir = function(fname)
      local root_files = {
        'config.py',
        '.git'
      }
      return util.root_pattern(unpack(root_files))(fname) or util.find_git_ancestor(fname) or util.path.dirname(fname)
    end,
  },
  docs = {
    description = [[
https://github.com/swyddfa/esbonio
    
A Language Server that aims to make it easier to work with Sphinx documentation projects in editors that support it.
    ]],
  },
}
```

**Comment by alcarney** [comment]
@cathaysia The language server sends all its log messages over the LSP protocol as `window/logMessage` notifications. In VSCode these are easily found in the `Output` panel - I haven't yet found the `nvim` equivalent to this.

However, there is a command `:LspInfo` that opens a window with some details about your language clients - including the path to where the `nvim` language client saves its logs. Note, this log file will contain a lot more than just `window/logMessages`, so you may have to do some digging to find the Sphinx specific messages.

![image](https://user-images.githubusercontent.com/2675694/141205772-3b77edc2-7beb-41ce-98a1-407650b6b2fd.png)

Hope that helps!

**Comment by cathaysia** [comment]
emm, sorry for too later. I'm waitting for https://github.com/neovim/nvim-lspconfig/pull/1292 and https://hub.fastgit.org/williamboman/nvim-lsp-installer/pull/253

Today, I reconfigurate this, but error still. So I made a empty sphinx project by sphinx-quickstart, then open init.rst, it works!

But it can't work when I open it in my project, I guess my conf.py add too much plugins, so it maybe consider as a bug?

And last, all logs that nvim output never contain any log of esbonio. :(

Sorry for my later again.

**Comment by alcarney** [comment]
> Sorry for my later again.

No worries :) 

> that nvim out never contain any log of esbonio

Now that I think about it, the language server doesn't produce many logs by default, you need to set the `server.logLevel` initialization option to `debug` to get most of the info. Something like this should work

```lua
lspconfig.esbonio.setup {
  init_options = {
    server = {
      logLevel = "debug"
    }
}
```
Additionally, you might also have to up the log level of `nvim` itself - have you tried following [these debugging steps?](https://github.com/neovim/nvim-lspconfig/#debugging)

> I made a empty sphinx project by sphinx-quickstart, then open init.rst, it works!

That's good to know! :smile: 

> But it can't work when I open it in my project, 

Hmm ... my guess is you're hitting one of two issues...

- `nvim` is using a different Python interpreter to the one where you have sphinx and/or its plugins installed - are you using a virtual environment? If so, you can override the default `cmd` to force `nvim` to use the right one
  ```lua
  lspconfig.esbonio.setup {
    cmd = { '/path/to/virtualenv/bin/python', '-m', 'esbonio' }
  }
  ```
- Or the language server isn't able to understand the structure of your project - where your conf.py is, the folder containing your `*.rst` files etc. This can be fixed by setting the `sphinx.confDir` and `sphinx.srcDir` initialization options 
  ```lua
  lspconfig.esbonio.setup {
    init_options = {
      sphinx = {
        confDir = "/path/to/docs",
        srcDir = "${confDir}/../docs-src"
      }
    }
  }
  ```
  See [here](https://swyddfa.github.io/esbonio/docs/latest/en/lsp/editors/index.html#initialization-options) for full details on the supported values

**Comment by cathaysia** [comment]
Thanks, I used my project in docker ever, I forget it. I recreate a venv and install requirements.txt, then it works. :)

Thanks for your patent. :)
