### ISSUE TITLE
Language status items disappear on Windows

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#458]
As raised in #326 

> The `{}` next to the language disappear from the statusbar after the first build and stay invisible for consecutive builds.

I *think* this is due to the client/server mis handling windows style paths

**Comment by alcarney** [comment]
@martinpakosch I've done some debugging and I think I've found the cause.

In your single root, auto-path-detection example,
```
[esbonio.lsp] Workspace root 'file:///c%3A/Users/xxxx/Sandbox/xxxx/xxxx/mylib'   
                                      ^
[client] Build complete {
  "config": {
    "sphinx": {
      "buildDir": "c:\\Users\\xxxx\\AppData\\Roaming\\Code\\User\\workspaceStorage\\136dd8f8fc7ff9a64b42dc0bce04fa7c\\swyddfa.esbonio\\sphinx\\html",
      "confDir": "c:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\source",          
                  ^
      "doctreeDir": "c:\\Users\\xxxx\\AppData\\Roaming\\Code\\User\\workspaceStorage\\136dd8f8fc7ff9a64b42dc0bce04fa7c\\swyddfa.esbonio\\sphinx\\doctrees",
      "srcDir": "c:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\source",
    },
  },
}
``` 
The workspace root as set by VSCode uses a little `c` for the drive name and since the language server isn't given any explicit configuration, it takes that root as a base and so all dervied paths (`srcDir`, `confDir` etc.)  also use a little `c`. Everything lines up, all is well.

In your single-root, explicit paths example
```
[esbonio.lsp] Workspace root 'file:///c%3A/Users/xxxx/Sandbox/xxxx/xxxx/mylib' 
                                      ^
[client] Build complete {
  "config": {
    "sphinx": {
      "buildDir": "c:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\build\\html",
      "confDir": "C:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\source",
                  ^
      "doctreeDir": "c:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\build\\doctrees",
      "srcDir": "C:\\Users\\xxxx\\Sandbox\\xxxx\\xxxx\\mylib\\docs\\source",
}
```
The workspace root as before uses a little `c` as the drive name, but now the language server is given explicit paths to use which use an uppercase `C`! Unfortunately, this tiny mismatch is enough to trip the extension up and think it should hide the language status items for your rst files.

Obviously a proper fix is needed, but as a quick test do you want to try your single-root explicit path example but with a lower case `c` for the drive name? You might also find that the preview magically starts working again :crossed_fingers:

To fix your multi-root examples I'm fairly sure some changes in the language server (#467) will also be required.

**Comment by martinpakosch** [comment]
Hi @alcarney,

took me some time to find some time 😱😁 but I can confirm your debugging. Everything starts to work nicely incl. the preview when I use a lower-case `c` drive-letter in my explicit paths.
