### ISSUE TITLE
Support for the new intersphinx syntax (`:external:` role)

### ISSUE THREAD

**Issue by stsewd** [swyddfa/esbonio#464]
Sphinx 4.4 introduced a new syntax for using intersphinx (the `:external:` role) https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#explicitly-reference-external-objects.

Basically:

- ``:external:domain:reftype:`target` ``
- ``:external:reftype:`target` ``
- ``:external+invname:domain:reftype:`target` ``
- ``:external+invname:reftype:`target` ``

Esbonio should

- Suggest `:external:` when typing `:`
- Suggest the intersphinx projects when typing `:external+` (or maybe even when typing just `:external`)
- Suggest all roles as usual after `:external:`
- Don't include intersphinx projects when suggesting targets, since the `invname:target` syntax doesn't work when using the external role

**Comment by stsewd** [comment]
The `:external:*` roles are resolved dynamically, that's why they aren't listed in the normal registry

https://github.com/sphinx-doc/sphinx/blob/ae42de48eba28718ba4a2f91945a2800ff7c48df/sphinx/ext/intersphinx.py#L467-L478

I guess esbonio needs a way for extensions to register roles, like a `add_role_completion_provider`?

https://github.com/swyddfa/esbonio/blob/26d972f529e3babbecc1e3a0a5b5b5c076ba8a81/lib/esbonio/esbonio/lsp/roles.py#L139

**Comment by alcarney** [comment]
> I guess esbonio needs a way for extensions to register roles, like a `add_role_completion_provider`?

Yes, in #453 I've just refactored support for directives and made it possible for 1st and 3rd party extensions to contribute directive completion suggestions. Once a similar refactoring for roles lands, adding support for this should be relatively straightforward.

**Comment by alcarney** [comment]
With #495 it should now be possible to implement this - would you be interested in having a go? 🙂

**Comment by stsewd** [comment]
> would you be interested in having a go? slightly_smiling_face

would love to!  I'll give it a try next week.
