### ISSUE TITLE
Switch Changelog Format to Markdown 

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#483]
At the risk of breaking the release pipelines (again! 😬) I think it would be worth switching the format of the changelog over to markdown. 

- rst is overkill for a set of release notes
- It looks like towncrier [can be configured](https://towncrier.readthedocs.io/en/latest/markdown.html) to output notes in markdown
- It would further simplify the release process, removing the need to install pandoc and convert the notes to markdown.
- It’s an excuse to add `myst-parser` to the docs and start seriously thinking about #312

**Comment by astrojuanlu** [comment]
Do you accept PRs for this one?

**Comment by alcarney** [comment]
Sure! :)
