### ISSUE TITLE
Extension can hang while checking Python version

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#493]
```
[client] Python extension is available
[client] Activating python extension
[client] Running Command: /.../bin/python -c import sys ; print("{0.major}.{0.minor}.{0.micro}".format(sys.version_info))
```
If this command fails (such as when the configured Python does not exist), then the extension will hang as the error is not appropriately handled

**Comment by lextm** [comment]
A separate but related topic is that I found `promisify(child_process.execFile)` a ridiculous wrapper that cannot throw critical errors out (if you happen to quote the last parameter as `"import ....."`. Pretty sad that it is not a reliable way yet to perform just the essential tasks like spinning out another process.

**Comment by alcarney** [comment]
This will no longer be an issue when the VSCode extension hits v1.0
See #609 for more details
