### ISSUE TITLE
Esbonio in Sphinx multiprocess mode eats up memory

### ISSUE THREAD

**Issue by twodrops** [swyddfa/esbonio#502]
One of our users complained that on a machine with 504GB RAM and > 72 cores  😱  Esbonio takes up all the memory. 

![image](https://user-images.githubusercontent.com/103930/204332783-409176c7-ba96-47f9-8093-f3e322ac8b7c.png)

To quote our user:
>We just see that Esbonio is suddenly starts spinning wild (see above), spawns dozens of sub-processes, which run malloc at full speed until no RAM is left for users. Screenshot above, when Esbonio is in "eating mode"

I found this interesting due to two reasons.

1. To see such a powerful machine where Esbonio is used :)
2. A pointer to a potential problem when `esbonio.sphinx.numJobs` is used in Esbonio.

For the first step, we will set `esbonio.sphinx.numJobs` to a fixed number and not `0` so that Sphinx/Esbonio does not start using all the available cores.

We are analysing this problem now and will get back when we have some results.

**Comment by alcarney** [comment]
> on a machine with 504GB RAM and > 72 cores, Esbonio takes up all the memory.

Yikes!

> We are analysing this problem now and will get back when we have some results.

I'll be interested to see what you find, simply running esbonio with `esbonio.sphinx.numJobs = 0` for a bit on my laptop doesn't appear to be enough to reproduce the issue...

**Comment by twodrops** [comment]
@alcarney I realized that esbonio always starts several forked child processes. Is this normal?
This is the case with `esbonio.sphinx.numJobs:"1"`
![image](https://user-images.githubusercontent.com/103930/206639003-9ab9cddd-536e-4bb3-a73e-c3762b533b52.png)


Tested with 0.14.3, 0.15.0

**Comment by alcarney** [comment]
> Is this normal?

I'm going to say... yes

However, I don't think these are child processes, but rather background threads in the same process. `htop` by default will also show threads, which can be switched off by pressing `H`. When I do this I see only a single entry for `esbonio`

I am however, slightly surprised at the number of threads in your screenshot... from the top of my head I can only account for 3, the main thread (shown in white) and the 2 threads in the thread pool that `pygls` uses.
![image](https://user-images.githubusercontent.com/2675694/206811077-8b3f2d0f-083b-4d01-a6f1-552bcb6bf5bf.png)

I don't suppose you're using any Sphinx extensions that would be spinning up threads of their own?

**Comment by alcarney** [comment]
Closing as I don't think there is anything Esbonio can do about this, plus with the new architecture in `1.0`, sphinx processes are now separate from Esbonio's process so they should behave the same as upstream Sphinx.

**Comment by twodrops** [comment]
@alcarney Great! Thanks for the update on the new 1.0 architecture. Do you have a rough timeline for 1.0 release? I checked this out already https://github.com/swyddfa/esbonio/issues/901

**Comment by alcarney** [comment]
I definitely want to release it this year, but can't get much more specific than that... yet.
