### ISSUE TITLE
How to know live preview server port?

### ISSUE THREAD

**Issue by hongquan** [swyddfa/esbonio#594]
I often work with VS Code Remote Development (through SSH). In this mode, the Esbonio extension runs in remote machine, so live preview cannot be accessed (due to NAT). I want to configure VS Code "port forward" to see the preview, but don't know which port.

**Comment by alcarney** [comment]
Interesting... I wonder if this is something extension could configure automatically.... :thinking: 

Anyway, if you increase the logging level by setting `esbonio.sever.logLevel = "debug"` you should see the port number printed in Esbonio's output panel.
![image](https://github.com/swyddfa/esbonio/assets/2675694/1244f029-92b0-4c7a-9657-86dbae9c7423)

**Comment by hongquan** [comment]
Thank you, @alcarney

**Comment by red8888** [comment]
@hongquan do you have this working in a dev container? I think I might be experiencing the same thing: https://github.com/swyddfa/esbonio/issues/727. What did you have to do to get this to work?

@alcarney does it use a static port or a dynamically generated one? I want my dev container to launch with everything already hooked up if thats possible.

**Comment by red8888** [comment]
This is odd the docs say I can configure this https://docs.esbon.io/en/release/lsp/reference/configuration.html#preview

But "esbonio.preview.wsPort" does not appear to be a valid setting vscode is accepting.

**Comment by hongquan** [comment]
@red8888 The port is not static to configure port forwarding, so I just stop using this VS Code extension's preview feature. I do separately in command line instead.
