### ISSUE TITLE
Feature request: get list of references in project

### ISSUE THREAD

**Issue by hwayne** [swyddfa/esbonio#611]
It would be really helpful if I could use telescope to jump straight to a reference, like `.. _operators::`. I tried using telescopes `builtin.lsp_workspace_symbols` but I got the error

> [telescope.builtin.lsp_*]: server does not support workspaceSymbolProvider

Apologies if this already exists and I just don't know how to call it right :)

**Comment by alcarney** [comment]
Unfortunately, the server doesn't support workspace symbols yet. :/ 

Hopefully it is something that can be added in the not too distant future - though it will likely be part of the next major version which is currently under development.

**Comment by alcarney** [comment]
An initial `workspace/symbol` implementation is now available in the [`1.0.0b1`](https://pypi.org/project/esbonio/1.0.0b1/) pre-release version of `esbonio`

**Comment by alcarney** [comment]
Closing as `workspace/symbol` has been implemented in the pre-release and #210 tracks the `textDocument/references` request
