### ISSUE TITLE
Sphinx 7.x support

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#637]
At some point in the 7.x cycle Sphinx [started using `pathlib.Path` like](https://github.com/sphinx-doc/sphinx/blob/fcc38997f1d9b728bb4ffc64fc362c7763a4ee25/sphinx/application.py#L152) objects to represent paths instead of strings.

I've not confirmed this, but there is a chance this will lead to parts of the `0.16.x` version of the language server starting to break with the latest versions of Sphinx. 

Version `1.0` of the language server will be the first version to officially support the latest `7.x` releases of Sphinx.

**Build Output**
~With Sphinx 7.x, esbonio is no longer removing control characters from the output~ As of `1.0.0b1`, esbonio now handles the build output correctly

<details><summary>Example</summary>

```
[2K
writing output... [ 86%]
env/lib64/python3.11/site-packages/sphinx/ext/autosummary/templates/autosummary/class

[2K
writing output... [ 93%]
env/lib64/python3.11/site-packages/sphinx/ext/autosummary/templates/autosummary/module

[2K
writing output... [100%]
index

```

</details>

**Comment by AA-Turner** [comment]
The first release to do so was 7.2.0; though note that 7.2.3 and onwards use a mildly awful technique to expose both a ``str`` and ``Path`` interface, which is scheduled for removal in Sphinx 8. So supporting ``Path`` should still be planned, but may be less urgent.

A

**Comment by alcarney** [comment]
Sphinx `7.x` seems to work well with the latest pre-release versions of `esbonio`
