### ISSUE TITLE
Publish Esbonio VS Code extension on Open VSX registry

### ISSUE THREAD

**Issue by marcel-22** [swyddfa/esbonio#641]
Could you please publish Esbonio (and any updates) on the [Open VSX registry](https://open-vsx.org/), once the major version 1.0 is released?

The VS Code Marketplace is for use with Microsoft Visual Studio products only. The Open VSX Registry is a community driven and fully open platform for publishing and consuming VS Code extensions.

**Comment by alcarney** [comment]
Sure! as mentioned in #550, I'm all for making Esbonio more widely available :) . I hadn't rushed into it though as it sounded like the registry [was in trouble](https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg) but it appears as though that's mostly resolved now?

> once the major version 1.0 is released?

I'd even be open to trying a few pre-releases, as I expect it will take a few tries to get it right

**Comment by marcel-22** [comment]
Thanks! Looks like the Open VSX Registry is saved with the [announcement](https://newsroom.eclipse.org/news/announcements/open-vsx-registry-vendor-neutral-open-source-alternative-visual-studio-0) of a new own working group.

**Comment by tchernobog** [comment]
@alcarney I requested addition ad-interim to the open-vsx common registry.

This is obviously just a temporary solution, but being the author you are the only one that can go through the steps at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by alcarney** [comment]
I'll aim to get the next pre-release published on open-vsx :crossed_fingers:

**Comment by alcarney** [comment]
All being well you should now be able to install `v0.93.2` from the [Open VSX marketplace](https://open-vsx.org/extension/swyddfa/esbonio)! Feel free to open an issue if there are any problems :)
