### ISSUE TITLE
python.exe with space in path

### ISSUE THREAD

**Issue by neil-benn** [swyddfa/esbonio#658]
Hello,

  I've pulled in esbonio as part of a module related to restructured text and the issue is that because the python is in 'program files' th python executbale path is not escaped with speechmarks.  Therefore I get:

```
[Log - 11:27:52 AM] Server start command: C:\Program Files\Python311\python.exe -m esbonio
[Log - 11:27:52 AM] LanguageClientOptions: {"documentSelector":[{"scheme":"file","language":"restructuredtext"},{"scheme":"file","language":"python"}],"initializationOptions":{"sphinx":{"srcDir":null,"confDir":"","forceFullBuild":true,"numJobs":1,"buildDir":null},"server":{"logLevel":"error","logFilter": ],"hideSphinxOutput":false,"enableScrollSync":true}},"outputChannel":{"name":"Esbonio Language Server"}}
[Log - 11:27:52 AM] Starting Language Server
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
```

  Is this something esbonio related or is it how vs code or the restructured text extension is calling esbonio to start it?

Regards,

Neil

**Comment by alcarney** [comment]
I believe [this](https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/406) is the issue you are experiencing. 

It is down to how the restructured text extension is starting the language server and so unfortunately isn't something that can be fixed from this repo.

**Comment by neil-benn** [comment]
Hello,

  Oh well thanks, the replies on that link we're pretty negative so I'll just uninstall the extension.  Thanks for finding that, the fix is obviously easy but the will to fix isn't there.

  Never mind.

Cheers,

Neil

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alcarney** [comment]
You might want to consider trying the [Esbonio](https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio) extension which is part of this repo - however it will only provide the `esbonio` language server and not the other tools like `doc8` or `rstcheck`

**Comment by neil-benn** [comment]
Hello,

  Thanks it's the rst stuff I need mostly but I'll see what esbonio on it's own does.

Cheers,

Neil

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alcarney** [comment]
No worries! :)
