### ISSUE TITLE
reStructuredText ecosystem changes in 2024

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#708]
Esbonio evolves very fast, so it seems to be the right time to review the ecosystem and plan out the future for all end users.

> Last review was tracked in #279 

I think the ideal arrangement in 2024 might look as below,

|                     | vscode-restructuredtext | esbonio            | vscode-rst |
| ------------------- |:-----------------------:|:------------------:|:------------------:|
| language server     | | Y
| section navigation  | | Y | Y
| syntax highlighting | | | Y
| live preview        | | Y
| conf.py selection   | Y*
| no conf.py mode     | Y*
| sync scrolling      | | Y
| show source         | Y* (#710)
| link editing        | Y
| linter integration  | Y (doc8/rstcheck/rst-lint)
| list editing        | Y
| table editing       | Y, from TatsuyaNakamori
| section header editing | Y

Features marked with `Y*` might be later migrated to esbonio if needed.

Another important change we might consider is to host the documentation together, likely on restructuredtext.net.

**Comment by lextm** [comment]
The very first change made in vscode-restructuredtext is that prerelease version 190.1.17 is shipped without live preview and language server features. Instead, this version recommends esbonio latest prerelease version to be installed. Once more testing is finished and no significant issue is there, a stable version will be published.

**Comment by q-wertz** [comment]
Maybe a stupid question, but I can find the esbonio extension in the VSCode [marketplace](https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio) but not in VSCode itself.
Due to this, reStructuredText Pre-Release v190.1.20 is not working anymore.
I'm using VSCodium version 1.85.2 with the official VSCode marketplace...

Am I missing something (e.g. I need VSCode >=1.86.0)? :sweat_smile: 

EDIT: installed it now using the .vsix file... But cannot get it up and running...

**Comment by lextm** [comment]
> I'm using VSCodium version 1.85.2 with the official VSCode marketplace...

At least, LeXtudio Inc. and all its VS Code extensions only support VS Code. VSCodium isn't a supported platform for us.

**Comment by alcarney** [comment]
> Am I missing something (e.g. I need VSCode >=1.86.0)?

Your VSCodium version should be fine, if I remember rightly the esbonio pre-release only requires 1.82.0+, so no idea why it's not showing for you sorry.

> EDIT: installed it now using the .vsix file... But cannot get it up and running...

Glad to hear you managed to get it installed at least, are there any specific errors you can share?

The first-run experience isn't the best at the moment... a common issue is that the extension isn't using the correct Python environment for your project, have you chosen one using the `Python: Select Interpreter` command?

**Comment by q-wertz** [comment]
As far as I could see the esbonio server didn't even start to run (nothing in the Status Bar as with stable and no previews only an empty Preview). 

I didn't run the `Python: Select Interpreter` command...

I already rolled back to stable. If you are interested in me trying it again I can do, but if you know about some kind of bugs I would leave it in it's current state :sweat_smile:

**Comment by lextm** [comment]
Just released vscode-restructuredtext 190.2.0 stable release, and ended the transition tasks there.

@alcarney More users will be driven toward the latest prerelease build of this Esbonio VS Code extension in the coming months. You might consider increasing release frequency to ship bugfixes quicker.

BTW, my team is willing to help on bugfixes but we couldn't get the development environment stabilised. Will write to you via emails with more details.

**Comment by alcarney** [comment]
@lextm ok thanks, will keep that in mind...

>  but we couldn't get the development environment stabilised

Can't say I'm surprised, any docs that do exist about dev envs will be wildly out of date by this point :sweat_smile: 
No promises as I've not had much luck in the past with them, but would a devcontainer definition be useful to you at all?

**Comment by lextm** [comment]
@alcarney we didn't yet switch to devcontainer.

Close this item now. If there are any future action items, will create new issues to track them.
