### ISSUE TITLE
[Task] Revise tags for clarity

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#738]
Two items might be considered to improve the tags in this repo.

- [ ] Add a new `triage` tag (used in #737), so that new issues created from the templates can be marked as before triage. Once triaged, this tag can be removed from the issue, while other supporting tags can be added accordingly.
- [ ] Change a few tags so that they can be grouped together,
  - `conda` might be renamed to `env:conda`, so that later `env:venv`/`env:pipenv`/`env:poetry` can be added.
  - `macos` might be renamed to `os:macos`.
  - `windows` might be renamed to `os:windows`.
  - `vscode` might be renamed to `ide:vscode`, so that later `ide:emacs` and similar can be added.

**Comment by alcarney** [comment]
Good idea! 

I think this is done - see https://github.com/swyddfa/esbonio/issues/labels let me know if you think I missed any
