### ISSUE TITLE
Running Esbonio Preview on Codespaces doesn't work

### ISSUE THREAD

**Issue by dp-sgr** [swyddfa/esbonio#896]
### Expected behavior

The preview of a a rst file should be displayed.

### Actual behavior

The Preview is broken.

The files are build and i can see a running process/automatically forwared port for esbonio:

<img width="812" alt="image" src="https://github.com/user-attachments/assets/567f9074-4ab2-4c43-9bb9-c094ebe5c4f4">

The preview is generated from an iframe and i believe that the problem is, that the url to the html page is statically mapped to localhost:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/7503f5e0-5a36-4586-9f59-4f80b46c6262">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/ee558884-70db-4449-b740-c55510c495ee">

----------

Opening the preview in another tab served from the routed Codespace works as expected.
Its only the build-in preview tab in vscode which doesn't work.

-----------

I've investigated a little bit.

As far as i can interpret the current esbonio code localhost is hardcoded and there is some additional logic when serving via localhost or not. Therefore this should be the problem.

The VsCode LivePreview plugin uses the method:

**asExternalUri**

In the env object of vscode (sorry there was no direct hyperlink to the function. Just search for "asExternalUri"):

https://code.visualstudio.com/api/references/vscode-api#env

LivePreview Ref:
https://github.com/microsoft/vscode-livepreview/blob/main/src/connectionInfo/connection.ts#L85

---------------

Maybe this helps a bit. But ive never wrote a vscode plugin before. I din't find any other issues regarding Codespaces or Dev Containers. 

### Log output

```shell
Logs are ok and the html files are all generated. 
This is only a "routing" issue of the preview url in codespaces.
```

**Comment by alcarney** [comment]
Thank you for such a detailed issue report!

Can I just check which version of the Esbonio extension you are using?

While I've never tried Codespaces myself, I have been using the pre-release version of the extension (`v0.90+`) with a Dev Container and the preview seems to work ok there. But then again maybe since the container is still on my machine localhost would work fine... :thinking:

Thanks also for finding `asExternalUri`, that looks like it's going to be useful!

**Comment by dp-sgr** [comment]
Hi @alcarney thanks for the quick response.

I've used the latest released version of the extension (v0.11.0).

I installed v0.95.1 (pre-release). Now im getting the error/loading page of esbonio:

<img width="555" alt="image" src="https://github.com/user-attachments/assets/23fcfe91-5c73-481b-9166-7eae64b7d58b">


After enabling debug logging, i can see the following output in my Esbonio log:

```
[esbonio.PreviewManager] Previewing file: 'file:///workspaces/MyProject/source/index.rst'
[esbonio.SphinxManager] No applicable client for uri: file:///workspaces/MyProject/source/index.rst
```

Which should be this line here:
https://github.com/swyddfa/esbonio/blob/1c1e5b19d24703dd171b71f5e6dc36c6a3eade71/lib/esbonio/esbonio/server/features/sphinx_manager/manager.py#L244

After reloading the VsCode instance i get this output:

```
[esbonio.PreviewManager] Previewing file: 'file:///workspaces/MyProject/source/index.rst'
[esbonio.PreviewManager] Preview available at: http://localhost:45525/?ws=37923
[esbonio.PreviewManager] window/showDocument: ShowDocumentResult(success=True)
```


In both cases the "No Content found" loading/error page of esbonio doesn't change. opening another document just outputs the three lines from above .

When im opening the preview (in this case on the container http://localhost:45525/) from outside (with the codespace url) im getting a semi-corrupt output of the html files. Multiple assets are missing  (Images, Styles, and so on...).
<img width="257" alt="image" src="https://github.com/user-attachments/assets/8aa172d0-148c-468b-9cd0-9a32196b89a2">


I also noticed, that the "build" folder is missing even if defined in config. I even removed the folder (from previous builds). It seams that the rst files are now transpiled on-the-fly? Idk. Running the build manually still works fine.

All-In-All: I don't know where to start to debug further. Console outputs are looking ok for me. Only the Browser debug console outputs the following error:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/cbe63fa2-79d6-47f6-9532-b315032991cb">

But this could be an error because something before that call goes wrong.
The error hits every time im opening a new file to preview:
<img width="348" alt="image" src="https://github.com/user-attachments/assets/b38635d9-aad2-4d16-b61c-e981a51e2475">

**Comment by alcarney** [comment]
> I also noticed, that the "build" folder is missing even if defined in config

Unfortunately, there are some differences in configuration between the two versions. If you haven't found it already, [this page](https://docs.esbon.io/en/latest/lsp/howto/migrate-to-v1.html#configuration-changes) from the docs should tell you what you need to adapt your config to the pre-release version.

> When I'm opening the preview (in this case on the container http://localhost:45525/) from outside (with the codespace url) im getting a semi-corrupt output of the html files. Multiple assets are missing (Images, Styles, and so on...).

Looking at the screenshot, my guess is that the server hasn't run a full build yet... have you tried editing a file and saving it?

> Only the Browser debug console outputs the following error:

I don't immediately recognise those error messages :thinking:... perhaps we can ignore those for now.

**Comment by dp-sgr** [comment]
Sorry for the delay, didn't had time to try it out again.

My build with the pre-release now works now again (thanks for the new configuration docs page).

The preview doesn't work. Im again at the first error:
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/0f8f5bff-2fbd-4b85-83ea-21015a93a065">

Opening the forwarded address manually works as expected and i can browse the full generated html sphinx doc:
<img width="550" alt="image" src="https://github.com/user-attachments/assets/ed686eab-2a76-4305-949b-94baeecb912d">

Maybe its really only necessary to swap the direct url usage to the output of ```asExternalUri```?

**Comment by alcarney** [comment]
> My build with the pre-release now works now again

I could be wrong, but those screenshots look like they are coming from the stable version? (`0.11.0`)

> Maybe its really only necessary to swap the direct url usage to the output of asExternalUri?

I'm hoping that would be enough to at least get the preview to show up... I'm worried getting the websocket connection the pre-release version uses for synchronised scrolling to also work however might be less straightforward... or maybe not? Can't quite get my head around how things in this case :sweat_smile: 

Anyway, I can add a call to `asExternalUri` to the http url and see what happens - I assume you can install an extension from a `*.vsix` file in a Codespace?

**Comment by dp-sgr** [comment]
Sorry you are right. After to many restarts it may have installed the rtm release again.
I cleaned everything up & installed the pre-release again.

The result is the same but im getting the new fancy "No Content Found" page again:
<img width="455" alt="image" src="https://github.com/user-attachments/assets/734fbbdd-744e-4f91-b8f9-eddcab82d3c3">

<img width="663" alt="image" src="https://github.com/user-attachments/assets/cbca3cb2-b1e7-41c4-90ae-b9e79a5de9e2">

Opening the url directly works fine & im getting my doc:
(I can also click on the link in the log output and VsCode automatically redirects me to the Codespace url)
<img width="507" alt="image" src="https://github.com/user-attachments/assets/a50c98bf-38b6-41ec-833b-8d0a338ce9b0">

In the browser log there is the illegal value for linenumber every time im navigating to a rst file again. Because you mentioned the websocket synchronized scrolling, this maybe is a follow-up problem.
<img width="638" alt="image" src="https://github.com/user-attachments/assets/590c4916-861c-43d2-83a3-16b1f29a6e42">

When i open the preview page im now also getting a csp error which could also be the issue:
<img width="881" alt="image" src="https://github.com/user-attachments/assets/63ac14ec-fe6e-4606-8928-b97888708815">
<img width="431" alt="image" src="https://github.com/user-attachments/assets/6a604226-bdd0-4f07-a29c-6c78cbc6f88d">

The vscode extension seems to also work with web sockets and the external uri handling and its only slighty different. Maybe that helps? https://github.com/microsoft/vscode-livepreview/blob/main/src/connectionInfo/connection.ts#L97

To the VSIX part: I did't tried it yet but it seems like there is support for that.
<img width="231" alt="image" src="https://github.com/user-attachments/assets/33a1d525-a8ae-42d1-868a-b132a5c00e67">

**Comment by alcarney** [comment]
I've opened #905 which will hopefully fix this however, I'm not able to test it myself. Are you able to download [this vsix archive](https://github.com/swyddfa/esbonio/actions/runs/11094348486/artifacts/1992660653)?

It should contain a file `esbonio-0.95.3-dev905.vsix` that you can use with the `Install from VSIX...` function in your Codespace. Let me know if it fixes it for you :crossed_fingers:

**Comment by dp-sgr** [comment]
Sadly this doesn't work :/ 

Ive googled a bit and also found this issues (any many references issues to that issue):

https://github.com/microsoft/vscode-livepreview/issues/111

Seems to be a general issue with codespaces (When opening the site for the firs time, there is a custom "loading" screen from github). 
<img width="250" alt="image" src="https://github.com/user-attachments/assets/fe0531db-ee49-409c-b64f-2798a3a81bd5">


But even when i open the url manually and then re-load or close & open the preview again it doesn't work.
Im everytime getting the csp error (as mentioned in my last post):
<img width="742" alt="image" src="https://github.com/user-attachments/assets/008de16b-ced9-4dde-ab04-eeeb63d9c3a8">
This error occurs everytime im opening the preview.

The line error message always appears when opening a new rst file (doesn't trigger again when im doing something with the preview). -> This may be also an issue but i think it isn't a problem for the preview which is my main importance.


Idk what part of the preview process triggers the error (I don't know how to debug extensions proberly). But i found this line:
https://github.com/swyddfa/esbonio/blob/971fb914efa7ec10818008ed6fb29efa9b72110a/code/src/node/preview.ts#L204
Which maybe also leads to an error because of:

> frame-src http://localhost:*/

Maybe there are multiple references to localhost? 


I also forked your demo and add a devcontainer config. There i get the same error:

<img width="549" alt="image" src="https://github.com/user-attachments/assets/477a389f-4c2a-4491-8f4a-5167f766fa36">


Feel free to start a devcontainer from my fork. I pinned the version directly to the latest published preview. You can also uninstall the version and install the latest one from you via vsix.
https://github.com/dp-sgr/esbonio-demo

**Comment by alcarney** [comment]
> Feel free to start a devcontainer from my fork.

I tried, but for some reason it seems to crash out halfway through connecting... 
![Screenshot_20240930_191111](https://github.com/user-attachments/assets/23259e08-6ca5-419c-8c2b-dda9b6907163)

Despite what the error message says, I definitely have a working network connection :sweat_smile: 

> Which maybe also leads to an error because of:
>     frame-src http://localhost:*/

Ah, forgot about the CSP :man_facepalming:, yes that will definitely not help the situation. I've now made it so the CSP is derived from the result of `asExternalUri` - perhaps that will be enough?

You can find an updated version of the extension [here](https://github.com/swyddfa/esbonio/actions/runs/11112136584/artifacts/1997131778)

**Comment by dp-sgr** [comment]
Ok strange :D Never had this issue before.

The new vsix doesn't change a thing. I looked at the iframe and the new csp value. There is now everything configured proberly (in my opinion)
<img width="737" alt="image" src="https://github.com/user-attachments/assets/73dbade5-959d-40c2-a05d-888f945e631c">

BUT: The nonce is empty in the style block:
<img width="209" alt="image" src="https://github.com/user-attachments/assets/e620de4c-82b5-4df0-87bc-c557345e2b1a">


Which should be (in this sample): nonce-RKoID2k8ViO38x9ZkK35ay6s5A0PUMcB

The same issues is on the script block:
<img width="241" alt="image" src="https://github.com/user-attachments/assets/6ae8a657-81b5-43f2-96e9-a70b483f9a23">

So maybe there is something wrong withe the nonce now (or this was even the issue before)? 
But idk why

**Comment by alcarney** [comment]
> The new vsix doesn't change a thing

That's frustrating :/

This missing nonce values are definitely a problem, without that script block the preview uri is never given to the iframe... :thinking: Like you I don't really know why the values are not there in the codespace, they seem to work as expected when the extension is run locally

![image](https://github.com/user-attachments/assets/25722b44-59a8-4055-9c64-deaae88b92be)

The issue I was having yesterday opening a codespace must be a Firefox issue, tried today with Chromium and it appears to work. I will see if I can figure out what is going on :crossed_fingers:

**Comment by alcarney** [comment]
I *think* I've found the root cause!

The code that pushes the uri to preview into the `<iframe>` checks to see if the message comes from the webview panel, or the page it is hosting. 
```js
      // Control messages coming from the webview hosting this page
      if (event.origin.startsWith("vscode-webview://")) {
          // ...
          viewer.src = message.show
          // ...
        }
      }

      // Control messages coming from the webpage being shown.
      if (event.origin.startsWith("http://localhost:")) {
        if (message.ready) {
          // ...
          vscode.postMessage({ ready: true })
        }
      }
```

However, when running in Codespaces the webview message origin is something like `https://1dd71hqg25q30t1qeadg0bqr2efk63ba2nu4g8hp18t0tbd68pl1.assets.github.dev` and the webpage message origin is something like `https://shining-rotating-banana-5x4r123fq72744g.github.dev/`

So, now it's "just" a case of tracking down all the assumptions broken by Codespaces :sweat_smile:

**Comment by alcarney** [comment]
I think I've got it! Do you want to try the [latest build](https://github.com/swyddfa/esbonio/actions/runs/11195371197/artifacts/2019466956) and see if it works for you?

Unfortunately, you will have to open the two port-forward links in a new tab and reopen the preview window before it will work though

**Comment by dp-sgr** [comment]
That looks very good. I can now see the preview in the demo fork & also in my custom repo.
Thank you very much for that 👍 

Opening the preview once in a seperate tab is the same workaroud as described here: https://github.com/microsoft/vscode-livepreview/issues/111

Maybe we can use the same (upcoming?) fix from the vscode-livepreview plugin to also get it working with esbonio :D
I subscribed to the issue and will keep an eye on that. I don't think we can fix that here if its an general issue with Codespaces.

-------

For now im very happy, because our users can view the preview.

One thing to mention: Even if i open both tabs separetely im getting a endless loading panel here:
<img width="922" alt="image" src="https://github.com/user-attachments/assets/708cdb6b-51b9-4fb2-b64b-5e1946f8c786">

This is mabe because of the following error:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/538f7668-066c-45bd-8e9e-6c1f47d80be9">
Or:
<img width="691" alt="image" src="https://github.com/user-attachments/assets/82a61fbf-3ce4-4db6-b131-dcda67f7be13">


So there is the NaN line issue again. -> That isn't a blocking issue for us but its maybe also only a little problem?
Clicking on other lines in the document is always resulting (understandably) in the same error.

**Comment by alcarney** [comment]
> That looks very good. I can now see the preview in the demo fork & also in my custom repo.

Glad to hear it!

> Maybe we can use the same (upcoming?) fix from the vscode-livepreview plugin to also get it working with esbonio

I'll definitely be keeping an eye out :crossed_fingers: 

> One thing to mention: Even if i open both tabs separetely im getting a endless loading panel here:
> This is mabe because of the following error:

Has the server done a full rebuild of the docs yet? I had to change some of the JS esbonio injects into the build. That error looks like the old code might still be present.

> So there is the NaN line issue again. -> That isn't a blocking issue for us but its maybe also only a little problem?
> Clicking on other lines in the document is always resulting (understandably) in the same error.

To be honest, I don't think I saw that error when testing it myself... I'm hoping it's just a side effect of the WebSocket connection failing :sweat_smile:

**Comment by dp-sgr** [comment]
@alcarney Yea. I dind't remove the build dir. After removing it & reloading the window it works now as expected.

Thank you again very much :)

This helps a lot
