### ISSUE TITLE
VS Code extension release notes should explicitly show bundled esbonio version

### ISSUE THREAD

**Issue by lextm** [swyddfa/esbonio#902]
https://github.com/swyddfa/esbonio/releases/tag/esbonio-vscode-extension-v0.95.2

This page doesn't show the bundled esbonio server version, while my guess is v1.0.0b7, not v0.16.5.

**Comment by alcarney** [comment]
They do when I [remember](https://github.com/swyddfa/esbonio/releases/tag/esbonio-vscode-extension-v0.95.0) to include it :sweat_smile:. It would be nice if it could be automated somehow...

**Comment by alcarney** [comment]
I've manually updated the release page for `v0.95.2` for now

**Comment by lextm** [comment]
Great. Close it now.
