### ISSUE TITLE
Some diagnotics missing (sphinx-needs)

### ISSUE THREAD

**Issue by AlexanderLanin** [swyddfa/esbonio#925]
### Expected behavior

I'd like to have sphinx-needs warnings available in esbonio 1.0

### Actual behavior

Warnings from sphinx-needs are NOT available in esbonio 1.0

### Analysis

`sphinx-needs` writes diagnostics data upon `build-finished` event.
`sphinx_agent` collects diagnostics data upon `build-finished` event.

Unfortunately they do it in incorrect order. `sphinx_agent` syncs diagnostics and THEN `sphinx-needs` generated diagnostics.

Links:
* https://github.com/useblocks/sphinx-needs/blob/d5e84653d971fbccf8b9cb2a7dbcba23d1cda77a/sphinx_needs/needs.py#L302
* https://github.com/swyddfa/esbonio/blob/f1ec7fc3791de996b782ee49cf159c3c56edf87e/lib/esbonio/esbonio/sphinx_agent/handlers/diagnostics.py#L48

I did not look into:
* Why it worked before
* Why it works for some people (unconfirmed)

Potential fix by adding a priority allows to push collecting diagnostics to the back:
`app.connect("build-finished", sync_diagnostics, priority=999)`

**Comment by alcarney** [comment]
> Potential fix by adding a priority allows to push collecting diagnostics to the back:

Yes, it certainly makes sense to have the `sphinx_agent` do its thing last - feel free to open a PR tweaking the priority if you'd like.

If not, I can do it when I switch back to working on `esbonio` in the next few weeks (currently focusing on updating esbonio to pygls `v2.0a2`, which requires I do some work in https://github.com/swyddfa/lsp-devtools first)
