### ISSUE TITLE
Preview -> Editor scroll sync too aggressive

### ISSUE THREAD

**Issue by alcarney** [swyddfa/esbonio#933]
### Expected behavior

Not to lose my editor position while working

### Actual behavior

![image](https://github.com/user-attachments/assets/00b7569f-7472-46f6-b1db-690726c66d64)

If I am working on a page where the source is much longer than the preview (so the webview is unable to align the preview with the source) and a build completes causing the preview to refresh, then the editor is instead synchronised to the preview state and I lose my position. - Very annoying!

The same is true if I switch to another file type e.g. python/vscode settings, if the preview refreshes then the editor is switched back to the source file for the current preview!

This issue is not limited to VSCode - see swyddfa/esbonio.el#5

**Comment by lextm** [comment]
A similar but distinct behaviour is jumping among the main .rst file and a bunch of referred .py files (examples can be found in lextudio/pysnmp) when scrolling down.

I believe that's a different issue to report but want to mention that here so you might think about a solution that might cover both.

**Comment by alcarney** [comment]
I assume that happens when using something like `.. autodoc::`?

I'm tempted to say the autodoc case is working as intended, I wanted it so that if you scrolled into a section that came from an `.. included::` file the corresponding source was revealed - it just happened that the solution also worked for autodoc so I left it in.

Though I can definitely appreciate that it could be annoying in some cases. :thinking:
